name: main
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        # TODO: work on windows-latest compatibility?
        os: [ubuntu-latest]
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']
        include:
        - os: macos-latest
          python-version: '3.9'
    runs-on: ${{ matrix.os }}
    name: test (py${{ matrix.python-version }} ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r requirements.txt
    - run: pip freeze
    - if: matrix.python-version != '2.7' && matrix.python-version != '3.5'
      run: make fmt
    - if: matrix.python-version != '2.7' && matrix.python-version != '3.5'
      run: make lint
    - run: python setup.py --version
    - run: make test-${{ matrix.python-version }}
  prerelease-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.x
    - run: pip install --pre -r requirements.txt
    - run: pip freeze
    - run: make fmt
    - run: make lint
    - run: python setup.py --version
    - run: make test
